<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: student.proto

namespace Student;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Student.StudentListResponse</code>
 */
class StudentListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Student.Student students = 1 [json_name = "students"];</code>
     */
    private $students;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Student\Student[] $students
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Student::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Student.Student students = 1 [json_name = "students"];</code>
     * @return RepeatedField<\Student\Student>
     */
    public function getStudents()
    {
        return $this->students;
    }

    /**
     * Generated from protobuf field <code>repeated .Student.Student students = 1 [json_name = "students"];</code>
     * @param \Student\Student[] $var
     * @return $this
     */
    public function setStudents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Student\Student::class);
        $this->students = $arr;

        return $this;
    }

}

