<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: student.proto

namespace Student;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Student.StudentResponse</code>
 */
class StudentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Student.Student student = 1 [json_name = "student"];</code>
     */
    protected $student = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Student\Student $student
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Student::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Student.Student student = 1 [json_name = "student"];</code>
     * @return \Student\Student|null
     */
    public function getStudent()
    {
        return $this->student;
    }

    public function hasStudent()
    {
        return isset($this->student);
    }

    public function clearStudent()
    {
        unset($this->student);
    }

    /**
     * Generated from protobuf field <code>.Student.Student student = 1 [json_name = "student"];</code>
     * @param \Student\Student $var
     * @return $this
     */
    public function setStudent($var)
    {
        GPBUtil::checkMessage($var, \Student\Student::class);
        $this->student = $var;

        return $this;
    }

}

