# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstudent.proto\x12\x07Student\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0eStudentRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"4\n\x0fStudentResponse\x12!\n\x07student\x18\x01 \x01(\x0b\x32\x10.Student.Student\"9\n\x13StudentListResponse\x12\"\n\x08students\x18\x01 \x03(\x0b\x32\x10.Student.Student\"7\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ndepartment\x18\x03 \x01(\t2\x97\x01\n\x0eStudentService\x12?\n\nGetStudent\x12\x17.Student.StudentRequest\x1a\x18.Student.StudentResponse\x12\x44\n\x0cListStudents\x12\x16.google.protobuf.Empty\x1a\x1c.Student.StudentListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'student_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STUDENTREQUEST']._serialized_start=55
  _globals['_STUDENTREQUEST']._serialized_end=83
  _globals['_STUDENTRESPONSE']._serialized_start=85
  _globals['_STUDENTRESPONSE']._serialized_end=137
  _globals['_STUDENTLISTRESPONSE']._serialized_start=139
  _globals['_STUDENTLISTRESPONSE']._serialized_end=196
  _globals['_STUDENT']._serialized_start=198
  _globals['_STUDENT']._serialized_end=253
  _globals['_STUDENTSERVICE']._serialized_start=256
  _globals['_STUDENTSERVICE']._serialized_end=407
# @@protoc_insertion_point(module_scope)
