<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: student.proto

namespace GPBMetadata;

class Student
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAF\x03\x0A\x0Dstudent.proto\x12\x07Student\" \x0A\x0EStudentRequest\x12\x0E\x0A\x02id\x18\x01 \x01(\x05R\x02id\"=\x0A\x0FStudentResponse\x12*\x0A\x07student\x18\x01 \x01(\x0B2\x10.Student.StudentR\x07student\"C\x0A\x13StudentListResponse\x12,\x0A\x08students\x18\x01 \x03(\x0B2\x10.Student.StudentR\x08students\"M\x0A\x07Student\x12\x0E\x0A\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\x0A\x04name\x18\x02 \x01(\x09R\x04name\x12\x1E\x0A\x0Adepartment\x18\x03 \x01(\x09R\x0Adepartment2\x97\x01\x0A\x0EStudentService\x12?\x0A\x0AGetStudent\x12\x17.Student.StudentRequest\x1A\x18.Student.StudentResponse\x12D\x0A\x0CListStudents\x12\x16.google.protobuf.Empty\x1A\x1C.Student.StudentListResponseb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

